# Generated by Django 2.1.1 on 2018-11-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDK_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answertable',
            old_name='modifiedTime',
            new_name='modificationTime',
        ),
        migrations.RenameField(
            model_name='commenttable',
            old_name='modifiedTime',
            new_name='modificationTime',
        ),
    ]
