# Generated by Django 2.1.1 on 2018-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDK_rest', '0002_auto_20181120_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagtable',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
